# Generated by Django 5.1.3 on 2025-05-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="login_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
