# Generated by Django 5.1.3 on 2025-05-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
